// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAq6FHDB3s_mWcE7ZSNifhSiOxUWrxQac',
    appId: '1:686951435694:web:b7ebb9bded06f1fa7e4c3f',
    messagingSenderId: '686951435694',
    projectId: 'eventride-cd0e9',
    authDomain: 'eventride-cd0e9.firebaseapp.com',
    storageBucket: 'eventride-cd0e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjs4VgCkDwQ_GyZntKXTOBmt7Co1sUkC8',
    appId: '1:686951435694:android:3d4b36a31821b4417e4c3f',
    messagingSenderId: '686951435694',
    projectId: 'eventride-cd0e9',
    storageBucket: 'eventride-cd0e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATekeW-v39LMXtMH9ZSJgEDdWGa_IPvdc',
    appId: '1:686951435694:ios:c75a8596b7a44fa77e4c3f',
    messagingSenderId: '686951435694',
    projectId: 'eventride-cd0e9',
    storageBucket: 'eventride-cd0e9.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATekeW-v39LMXtMH9ZSJgEDdWGa_IPvdc',
    appId: '1:686951435694:ios:c75a8596b7a44fa77e4c3f',
    messagingSenderId: '686951435694',
    projectId: 'eventride-cd0e9',
    storageBucket: 'eventride-cd0e9.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAq6FHDB3s_mWcE7ZSNifhSiOxUWrxQac',
    appId: '1:686951435694:web:8c063b51a9cea04c7e4c3f',
    messagingSenderId: '686951435694',
    projectId: 'eventride-cd0e9',
    authDomain: 'eventride-cd0e9.firebaseapp.com',
    storageBucket: 'eventride-cd0e9.firebasestorage.app',
  );
}
